AllStarLink/app_rpt

channels/chan_simpleusb.c
channels/chan_usbradio.c
include/asterisk/res_usbradio.h
res/res_usbradio.c

This refactors chan_simpleusb and chan_usbradio time functions into res_usbradio.

chan_simpleusb / chan_usbradio: Refactor time functions to res_usbradio

---

README.md

Remove extra `-` in dev instructions.

README.md: Correct phreaknet install parameters

---

apps/app_rpt.c

There appears to be many duplicate instances of the timer update logic.  This may be a cleaner less repetitive way?

app_rpt: remove duplicate timer code adding inline update_timer

---

.gitignore

This updates .gitignoreto add the directory .vs/
We already include .vscode/ for vscode.  I am adding .vs/ for visual studio.

Update .gitignore to add .vs/

---

configs/rpt/logger.conf

This updates logger.conf to add debug and verbose messages to the console.  This will help users experiencing problem to easily see debug and verbose messages.

Update logger.conf: Add debug and verbose to console

---

apps/app_rpt.c

Refactor `if()` for a bit more clarity.
Move mutex_unlocks() for clarity (and sanity)

app_rpt.c:  Refactor funcchar_common()

---

apps/app_rpt/rpt_telemetry.c

use `snpritnf()`
use `rpt_request_pseudo_chan()`

rpt_telemetry.c: use snprintf

---

apps/app_rpt.c

Function is called locked, should return locked

app_rpt.c: Incorrect unlock on failure return.  

---

apps/app_rpt.c

app_rpt.c: rxchannel_read remove incorrect unlocks.

---

apps/app_rpt.c

* Remove testing debug message that ran once per frame.
* Clean up debug messages for if scheduler is disabled.

app_rpt: Clean up a couple debug messages.

---

.dev/.clang-format

Some of the rules apparently did not make it into the PR.
Let's update these and see how CI behaves.

.clang-format: update rules

---

apps/app_rpt.c
apps/app_rpt/app_rpt.h
apps/app_rpt/rpt_cli.c
apps/app_rpt/rpt_config.c
apps/app_rpt/rpt_functions.c
apps/app_rpt/rpt_mdc1200.c
apps/app_rpt/rpt_uchameleon.c
apps/app_rpt/rpt_utils.c
apps/app_rpt/rpt_utils.h

Refactor `myrpt->macrobuf` to use `ast_str*`. 
Create function `macro_append()` for securely adding commands to the buffer.

app_rpt.c: use ast_str for macrobuf

---

apps/app_gps.c

Use ARRAY_LEN for strs                  
Match explode_string to rpt_utils.c version
limit checksum calc to sizeof buffer

app_gps.c: Use ARRAY_LEN for strs

---

apps/app_rpt.c
apps/app_rpt/app_rpt.h
apps/app_rpt/rpt_config.c
apps/app_rpt/rpt_functions.c
apps/app_rpt/rpt_telemetry.c
apps/app_rpt/rpt_utils.c
channels/chan_echolink.c
channels/chan_simpleusb.c
channels/chan_tlb.c
channels/chan_usbradio.c
channels/chan_voter.c
channels/xpmr/xpmr.c

Add buffer overflow protection to sscanf() string reads.

Multiple: Add string length protection to all sscanf() calls

---

apps/app_rpt.c
apps/app_rpt/rpt_telemetry.c
apps/app_rpt/rpt_utils.c
apps/app_rpt/rpt_utils.h

app_rpt.c: Remove update_timer()
rpt_utils.c: Add update_timer()

rpt_telemetry: Use update_timer() for timers, move update_timer() to rpt_utils.c

---

apps/app_rpt.c

In the original refactor of app_rpt for current versions of Asterisk, we hacked around the fact that AST_PBX_KEEPALIVE was removed back in https://github.com/asterisk/asterisk/commit/50a25ac8474d7900ba59a68ed4fd942074082435. At the time, there was no correct way to emulate what we were trying to do, as ast_pbx_run_args could only be used when the caller knew the channel wouldn't hang up in advance, and the PBX doesn't do that.
The hack at the time to compile was simply to call pthread_exit() to abort the PBX thread and prevent it from hanging up the channel as it would have when it cleaned up after dialplan finished. This was far from ideal as it was an unclean and improper PBX termination.
Since the PBX args interface doesn't allow setting an arg after the PBX has been started, we …

app_rpt: Properly work around removal of AST_PBX_KEEPALIVE.

---

apps/app_rpt/rpt_cli.c
apps/app_rpt/rpt_link.c
apps/app_rpt/rpt_manager.c
apps/app_rpt/rpt_telemetry.c

In correct size for array of strs

app_rpt.c: Correct malloc length for strs

---

apps/app_rpt.c
apps/app_rpt/rpt_link.c
channels/chan_simpleusb.c
channels/chan_voter.c

Noticed `ast_frdup()` can fail.  Add test for failure.

app_rpt.c: ast_frdup() test for failure to alloc

---

apps/app_rpt.c
apps/app_rpt/rpt_channel.c
apps/app_rpt/rpt_functions.c
apps/app_rpt/rpt_link.c
apps/app_rpt/rpt_mdc1200.c
apps/app_rpt/rpt_utils.c
apps/app_rpt/rpt_utils.h

Use `init_text_frame()` for all instances of text frames.
send text messages with rpt_qwrite() when writing to links

app_rpt: Use init_text_frame

---

channels/chan_simpleusb.c

By adding 1 null frame (typically at the beginning of a transmission), chan_simpleusb can then keep up with the usb device. Generally, the channel update is > 20ms (20.1ms -> 20.5ms) which allowed the usb buffer to empty. Relocation of the process transmit queue logic because we need to write frames even if we don't receive one. This eliminates the need to set snd_usb_audio lowlatency=0

chan_simpleusb: add 1 null frame when USB buffer is emtpy allowing for lowlatency=1

---

channels/chan_tlb.c

chan_tlb: Don't store pointer to channel.
chan_tlb was storing the channel pointer, which is invalid if a masquerade
occurs, such as in app_rpt's rpt_exec. This stored pointer was not necessary and
chan_tlb has been refactored to remove it.
Fixes #609

chan_tlb: TLB channel driver does not handle ast_channel_yank()

---

channels/chan_echolink.c

Cleanup empty queues and free memroy when hanging up.
mutex lock around `insque()` and `remque()` calls as they are in executed in different threads.
Add mutex lock around access to el_nodlist access.

chan_echolink: Address memory leak and code quality updates

---

apps/app_gps.c
configs/rpt/gps.conf

This change addresses two issues:
1. the [general] section should not have been marked as a template
2. adding additional sections resulted in crashes

gps.conf, app_gps: fix configuration issues and crashes

---

channels/xpmr/xpmr.c

At least partially addresses Issue https://github.com/AllStarLink/app_rpt/issues/526

xpmr.c: Prevent out of range reference to `pChan->pTxCode[i]`

---

apps/app_rpt/rpt_cli.c

Fixes issue rpt_cli: Add tab completion for node names #130

app_rpt: add cli completion for node names

---

channels/chan_simpleusb.c
channels/chan_usbradio.c

chan_usb*: fix incorrect mutex lock

---

apps/app_rpt.c

* Remove duplicated code by leveraging existing function.
* Reduce the scope of who and a few other variables where possible.

app_rpt: Remove duplicated code, narrow variable scope.

---

apps/app_rpt.c

app_rpt: Backout PR#601 - create conferences, not join.

---

channels/chan_echolink.c

Remove unused `el_rxqel`.  Turns out nothing is put on this queue

chan_echolink: remove dead code

---

channels/chan_echolink.c

An incoming EchoLink connection to a node already associated with another node with [many] linked nodes was triggering a crash.  The prime suspect for the crash was the el_text() function that was iterating over the linked nodes and generating text to be passed to connected EchoLink nodes.  This code was hard to read, had some fixed-sized buffers, and did a lot of memory copying.  The code has been reworked and appears to have resolved the crashes.
A handful of other changes, mostly for readability, are included.

chan_echolink: fix crash associated with incoming connection

---

channels/xpmr/xpmr.c
channels/xpmr/xpmr.h

Related to this issue :
https://github.com/AllStarLink/app_rpt/issues/526

xpmr.c: Replace `printf()` with `ast_log()` restoring logging.

---

channels/chan_echolink.c
channels/chan_tlb.c

The RTCP packet creation functions had a few math problems that resulted in sending a few additonal bytes of data at the end of the packet with some of those bytes being from uninitialized memory. This change corrects these issues and should also resolve a few valgrind errors that were reported.

chan_echolink, chan_tlb: Fix RTCP packet creation

---

channels/chan_echolink.c
channels/chan_tlb.c

Bit of cleanup and optimization

Cleanup chan_echolink and chan_tlb

---

apps/app_rpt/rpt_cli.c

Fixes Sort lstats Numerically by Node Number #37

app_rpt: Sort connections by node number

---

channels/chan_echolink.c

chan_echolink: Add callsign lookup for echolink nodes

---

apps/app_rpt.c
apps/app_rpt/app_rpt.h
apps/app_rpt/rpt_cli.c

Add command completion to the third argument.

app_rpt: add more command completion to "rpt cmd"

---

channels/chan_tlb.c

Update docs
Change RTP packet to type 2

chan_tlb: rtp packet type 2

---

apps/app_rpt.c

app_rpt: rpt_vars[]->ready never set true for remote.  Issue created by PR#532

---

apps/app_rpt.c
apps/app_rpt/app_rpt.h
apps/app_rpt/rpt_config.c
apps/app_rpt/rpt_config.h
configs/rpt/rpt.conf

Add config variable for DNS node lookup

---

configs/rpt/iax.conf

Trivial typo fix - patched because I couldn't find the file suggested :-)

iax.conf: Typo fix registartions -> registrations

---

apps/app_rpt.c
apps/app_rpt/rpt_telemetry.c
apps/app_rpt/rpt_telemetry.h
configs/rpt/extensions.conf
configs/rpt/modules.conf
configs/rpt/rpt.conf

Allow for Time Of Day to be generated from the dial plan. 
Based on https://github.com/AllStarLink/app_rpt/pull/688 (aka need to merge 688 first)

app_rpt: Add TOD to dialplan

---

channels/chan_usbradio.c

Match a few more differences between simplusb and usbradio.

chan_usbradio: Code quality - Match simpleusb

---

apps/app_rpt/rpt_telemetry.c

Asterisk complains about missing xml docs.  
Created by PR https://github.com/AllStarLink/app_rpt/pull/735

Add docs for `rpt_telem_time`

---

channels/chan_echolink.c

Fixes https://github.com/AllStarLink/app_rpt/issues/779

chan_echolink: Handle truncated call and name

---

apps/app_rpt.c

Optimize `ast_pbx_run_args` setup
Set tonezone for `genchannel` if tonezone is configured in rpt.conf.  We were only setting tonezone on `mychannel`.

app_rpt.c: Add missing CALLMODE_DOWN when autopatch setup fails.

---

channels/chan_simpleusb.c
channels/chan_usbradio.c

When writing out updated node/interface settings to the "simpleusb.conf" (or "usbradio.conf") files, we should only be updating values in the leaf category/stanza and not within any of the template category/stanzas.

chan_simpleusb, chan_usbradio: write tune settings only to node/interface
