AllStarLink/app_rpt

channels/chan_simpleusb.c
channels/chan_usbradio.c

chan_simpleusb and chan_usbradio should not activate the receiver 
when the carrierfrom and ctcssfrom are set to no.
This closes #329.

chan_simpleusb / chan_usbradio: Modify cos operation

---

res/res_rpt_http_registrations.c

When you start off with a "rpt_http_registrations.conf" containing an error and attempt to register then you may get back an unexpected response.  If you don't check for the unexpected then you can end up with a crash.  This change adds a missing check for the unexpected (lack of "data").

Fix issue where bad registration info leads to NULL dereference crash

---

apps/app_rpt/rpt_config.c

This updates app_rpt to use DNS SRV records when looking up a node by DNS.
The original code used the TXT record which was labeled for debugging purposes.  The original TXT lookup code remains and is switched off for now.
This closes #360

app_rpt: Update to use DNS SRV record

---

apps/app_rpt.c
apps/app_rpt/app_rpt.h
apps/app_rpt/rpt_config.c

This updates app_rpt to address a problem with looking up a 5 or 6 digit node from a 4 digit node. The 4 digit node could not lookup 5 or 6 digit nodes when it did not use an external nodes file. This would happen if you are not using the node updater and depending on DNS only.
The problem was associated with the internal 'longestnode' variable. We did not have an external file to determine the longest node number. In this case, the longest node was set to 4.
A new rpt.conf [general] item, max_dns_node_length, has been added with a default value of 6. The routines that determine the longest nodes will now MAX the value it determines with rpt_max_dns_node_length. The configurable item cannot be less than 4 or more then 63.
By default, this configurable item will not be in rpt_conf. It can …

app_rpt: Correct 5 digit node lookup from 4 digit node

---

res/res_rpt_http_registrations.c

The current HTTP registration timeout (5s) has proven to be too slow for some nodes.  Bump the timeout to 15s.

Increase HTTP registration timeout

---

apps/app_rpt.c

Fixes #365 
Checks if system is sending a beacon ID.

Remove tail when beaconing

---

configs/rpt/simpleusb.conf
configs/rpt/usbradio.conf
configs/samples/simpleusb.conf.sample
configs/samples/usbradio.conf.sample

This updates simpleusb and usbradio config files for missing parallel port options.

Update configs for missing options

---

apps/app_rpt/rpt_cli.c

This updates app_rpt to address a crash that occurred when using the rpt page command.
ast_sendtext should not require locking according to the documentation, but that does not seem to be the case. In some instances, the main processing loop had control of the channel. ast_sendtext would cause an assert abort in channel.c.
This was shown by the message ast_sendtext_data: Thread LWP 88692 is blocking 'Radio/usb_2231', already blocked by thread LWP 88688 in procedure ast_waitfor_nandfds.
Adding rpt_mutex_lock around ast_sendtext resolved the problem.
Corrected an if statement in the same routine that was already flagged in the code as a bug.
Remove chan_usbradio as a destination for paging.  chan_usbradio does not implement paging. Sending pages to chan_usbradio resulted in a stuck PTT. …

app_rpt: Correct crash when using rpt page

---

apps/app_rpt.c

When using "archivedir = /var/spool/asterisk/monitor" we create files in the [spool] directory. We are setting the filesystem permissions on the ".txt" files to be 0644.  We should do the same for the ".WAV" files.

Update the permissions of the "archivedir" .WAV files.

---

apps/app_rpt/rpt_bridging.c

This change restores the operation of the autopatch VOX function.
Changes were made in #363 to get the autopatch working.  Part of those changes did not correctly address the operation of the vox channel.  This change removes some of those changes and restores the operation of the vox channel.
For the vox channel to work properly, this change along with changes to the DAHDI driver are required.  The changes to the DAHDI driver are located at https://github.com/KB4MDD/dahdi-linux
We will be attempting to get these changes into the main DAHDI channel.
This closes #388

app_rpt: Correct VOX operation for autopatch

---

apps/app_rpt/rpt_manager.c

The rpt_manager_trigger() function uses ctime(3) to add formatted date/time strings for LastKeyedTime and LastTxKeyedTime.  Unfortunately, the returned strings include trailing '\n' characters that add empty lines to the output. This presents an issue as an empty line typically indicates the end of the AMI output.
This change removes the extra (unexpected) '\n' characters.

Fix LastKeyedTime/LastTxKeyedTime info in RPT events

---

utils/radio-tune-menu.c
utils/simpleusb-tune-menu.c

Adds a new "-n node" argument to the `simpleusb-tune-menu` and `radio-tune-menu` commands that allow one to [pre-]select the active device being displayed and updated.

Tune menus should allow specifying "node" to update

---

channels/chan_usrp.c

This updates chan_usrp to have debug messages for TX and RX on and off. The messages closely match those in chan_simpleusb and chan_usbradio. This indication is needed to help users troubleshoot problems when using this driver.
I also added a queue overflow warning message should the internal queue overflow.  This should never happen, but if it does, it needs to be reported.

chan_usrp:  Add TX/RX debug messages

---

channels/chan_simpleusb.c
channels/chan_usbradio.c

When the tune menus request that the current configuration settings be saved there is an assumption that each variable will be represented in the .conf file.  There is no reason that any variables missing from the .conf files cannot be added.

Tune menus will not always save settings

---

channels/chan_simpleusb.c
channels/chan_usbradio.c
utils/radio-tune-menu.c
utils/simpleusb-tune-menu.c

The `simpleusb-tune-menu` shows the current TX levels but only reports the current RX level when adjustments are being made.  The information is available and should be reported.

SimpleUSB: show RX level

---

apps/app_rpt.c
apps/app_rpt/rpt_config.c

Note: the crash that prompted this fix was a typo in the category declaration for a node (e.g. "[1234]\(node-NOTmain)").

Fix crash if "rpt.conf" cannot be loaded

---

apps/app_rpt.c
channels/chan_simpleusb.c
channels/chan_usbradio.c

app_rpt is not waiting long enough in rpt_setup_channels for chan_simpleusb to initialize the usb device before asserting PTT on/off.
This change adds a 250ms delay before asserting PTT on and another 50ms delay before asserting PTT off.
I believe the intention of the original code was to insure that the PTT was toggled immediately after the channel driver was created by app_rpt.
Testing by the effected users is needed. This may close #421 and #424.

app_rpt:  Channel initialization for PTT

---

configs/rpt/res_usbradio.conf
configs/samples/res_usbradio.conf.sample
res/res_usbradio.c

This updates res_usbradio to allow users to specify USB device descriptor(s) that can be used for interface devices. There are compatible chips that are not supported in the code. This will allow users to easily add the compatible chip(s).
This adds res_usbradio.conf for configuration. A sample configuration file was added.
Reworked the supported/known USB devices lookup.  The supported devices are now in an array.
This closes #359.

res_usbradio: Add ability to specify allowed vid:pid

---

channels/chan_usbradio.c
channels/xpmr/xpmr.c
channels/xpmr/xpmr.h
configs/rpt/usbradio.conf
configs/samples/usbradio.conf.sample

The ASL2 change (from https://github.com/AllStarLink/ASL-Asterisk/pull/34) did not get merged into the ASL3 source base. This commit effectivly pulls in those changes.
From: David Gleason <david@allscan.info>
Replace xpmr.c '#define XPMR_VOX_HANGTIME' with a new 'voxhangtime' cfg parameter set in usbradio.conf. When using usbradio in carrierfrom=vox mode this is the value the vox hang timer pChan->rxVoxTimer is set to in xpmr.c each time RX audio is detected. Making it configurable allows the default value of 2000mS to be reduced to a shorter time thereby preventing 2 seconds of silence being added to all node user transmissions. A value of 500mS seems to be much more optimal, and in my testing resulted in no false RX CD drops even when not talking. (xpmr.c's vox mode detects even quiet …

[ASL2 PATCH] Replace xpmr.c '#define XPMR_VOX_HANGTIME' with a new conf var

---

apps/app_rpt/rpt_channel.c

An ASL2 change (from https://github.com/AllStarLink/ASL-Asterisk/pull/19) was not fully merged into the ASL3 source base.  That PR included an correction to the morse code character timing, specifically the inter character delay.  This change updates the timing to match what's commonly understood (the space between two letters is equal to three dots).

[ASL2 PATCH] Update morse code character timing

---

apps/app_rpt/rpt_manager.c

This function returns char*, but the variable is typed const char* by mistake; this fixes that.
Resolves: #439

app_rpt: Fix variable typing issue.

---

apps/app_rpt.c

Addressing issue #447 
Restore in inadvertently removed break

Restore missing break in process_link_channels()

---

.github/workflows/main.yml
rpt_install.sh

It seems that /etc/init.d/asterisk restart is now returning nonzero, causing the build to abort. This action isn't actually even necessary, so we could remove it, or safely continue the build regardless of its return value.

CI: Don't restart Asterisk in the middle of the build.

---

channels/chan_usrp.c

This changes chan_usrp to report the queue overflow message as a debug message instead of a warning.  This message was not included in the original code.  It was added to aid in debugging future problems.
We are getting a burst of packets from analog_bridge that overflows the queue.  Analysis of this issue would require further knowledge of analog_bridge.  These packets do not cause a problem with the operation of the channel driver.
I have made it a debug level 1 message should there be a need to see this in the future.
The overflow message was using the wrong value for the queue threshold. This is corrected with this change.
This closes #437 and closes #442

chan_usrp: Change queue overflow to debug message

---

apps/app_rpt.c

* Add warnings if outstreamcmd fails to start.
* Fix handling if fork() fails.
* Use ast_safe_fork() instead of fork().
* Close all file descriptors in child before exec.
* Refactor kill(outstreamcmd) into helper function.
* If outstreamcmd fails to execute, don't continously try to restart it in a loop. Instead, log an error and give up.
Resolves: #338

app_rpt: Tighten logic for stopping outstreamcmd.

---

apps/app_rpt.c

As observed: address several locations where locks are held and should not be.

app_rpt: Add rpt_mutex_unlock at return locations

---

apps/app_rpt.c

l->chan can't be true if it was false.

app_rpt: Remove unreachable code

---

configs/rpt/usbradio.conf
configs/samples/usbradio.conf.sample

Should this really be inverted? Unless I missed it, I see no way in radio-tune-menu to swap the PTT logic

Do not default to inverted PTT

---

apps/app_gps.c
apps/app_rpt.c
apps/app_rpt/app_rpt.h
apps/app_rpt/rpt_functions.c
apps/app_rpt/rpt_telemetry.c
apps/app_rpt/rpt_translate.h
apps/app_rpt/rpt_utils.c
apps/app_rpt/rpt_utils.h
channels/chan_echolink.c
configs/rpt/gps.conf
configs/rpt/rpt.conf

This updates app_gps with the following changes:
Update the code to use the asterisk coding guidelines. Added documentation to all functions.
Added documentation to gps.conf.
Added functions: GPS_READ and APRS_SENDTT.
Added the cli command gps status.
Added the ability to select the primary or alternate symbol table. Replaced depreciated ast_gethostbyname.
Addressed issues with module unload not completing timely.
GPS_READ() function replaces the need to create the gps.dat file stored in the /tmp directory.  The application previously wrote to the disk once per second, which included a system call to rename a temporary file.
app_rpt and chan_echolink have been updated to use GPS_READ to retrieve the gps data, instead of reading a data file.
APRS_SENDTT(stanza, overlay) = callsign, …

app_gps: Code updates and documentation

---

apps/app_rpt.c
apps/app_rpt/app_rpt.h

Not sure how I missed the compiler warnings when I tested https://github.com/AllStarLink/app_rpt/pull/457
The changed timers are unnecessarily `long`.  We could alternately go with `long` for all timers if there is concern about expanding beyond 32767ms for any timer.  Currently all of them appear to fit in an `int`.

app_rpt.c: change timers of unnecessary long to int

---

channels/chan_tlb.c

Check the correct length to prevent over running the output pointer.

chan_tlb.c: finddelim update limit to length of strp from str

---

apps/app_rpt/rpt_uchameleon.c

This clearly should be strlen of the string.  
```
sizeof(&expect) = 8
strlen(expect) = 9
```
I suppose it "works" because the count is always 13? or the first 8 characters always match.

rpt_uchameleon.c: Incorrect use of sizeof()

---

utils/simpleusb-tune-menu.c

Update explode_string() to limit strp length.

simpleusb-tune-menu.c: Update explode_string()

---

utils/radio-tune-menu.c

Update explode_string to limit strp length.

radio-tune-menu.c: update explode_string()

---

utils/radio-tune-menu.c
utils/simpleusb-tune-menu.c

simpleusb-tune-menu.c: need include "asterisk.h"
As asterisk developer site says, you need to start with #include "asterisk.h" for the others to work.

radio-tune-menu.c: need include "asterisk.h"

---

apps/app_rpt/rpt_serial.c
apps/app_rpt/rpt_serial.h

`int serial_io(int fd, char *txbuf, char *rxbuf, int txbytes, int rxmaxbytes, unsigned int timeoutms, char termchr)` should be `const char *txbuf`.

rpt_serial.c: use const char * for txbuf

---

apps/app_rpt.c

Provide text error descriptions from the curl library.
Closes issue #490

app_rpt.c: perform_statpost - add verbose text to errors.

---

.dev/.codespellignore
apps/app_rpt.c
apps/app_rpt/app_rpt.h
apps/app_rpt/rpt_config.c
configs/rpt/rpt.conf

Allow replacement of GSM/WAV49 audio archives with other formats

---

channels/chan_voter.c

Check the correct length to prevent over running the output pointer.

chan_voter.c: finddelim update to length of strp from str

---

apps/app_rpt/app_rpt.h
include/asterisk/res_usbradio.h

While some may argue that a few known/understood compilation warnings are OK we get into trouble when stop looking for "new" warnings in build output that includes a number of "old" ones. The simple solution is to banish ALL warnings from the project and then treat any warnings as errors.
This PR addresses the `sys.io is not available on this architecture` warnings reported on `arm64` builds.

app_rpt: Don't emit warnings about <sys/io.h> being unavailable

---

channels/chan_echolink.c

Fix the define line continuation errors,
Fix pointer errors with ast_str calls

chan_echolink.c: fix typo in define EL_INIT_BUFFER

---

apps/app_rpt/rpt_functions.c
apps/app_rpt/rpt_telemetry.c

Addressing issue #481 
Looks like we are pointing to the wrong channel.

rpt_telemetry: Update PAGE command to use correct channel.

---

apps/app_gps.c
channels/chan_echolink.c

APRS location format is ddmm.hh (lat) or dddmm.hh (long) followed by the cardinal compass direction as N,S,E,W. The `hh` hundredths of minutes not thousandths as is the standard format. This fixes rounding and casting errors that causes the format to be wrong or slightly off.

Fix conversion errors for APRS coordinate format

---

configs/rpt/modules.conf

A number of Asterisk modules were deprecated (and removed) in 21.x.x and 22.x.x.  These changes update the ASL3 provided "modules.conf" file to sync with those changes as well as some overdue cleanup.
*** NOTE ***
The file currently includes some added content and a bunch of questions. For those reviewing the changes, your comments and guidance are welcomed.

modules.conf: update for Asterisk 22.x.x

---

apps/app_rpt.c
apps/app_rpt/rpt_cli.c
apps/app_rpt/rpt_config.c
apps/app_rpt/rpt_daq.c
apps/app_rpt/rpt_functions.c
apps/app_rpt/rpt_link.c
apps/app_rpt/rpt_link.h
apps/app_rpt/rpt_manager.c
apps/app_rpt/rpt_rig.c
apps/app_rpt/rpt_telemetry.c
apps/app_rpt/rpt_uchameleon.c
apps/app_rpt/rpt_utils.c
apps/app_rpt/rpt_utils.h

This is a follow on to PR https://github.com/AllStarLink/app_rpt/pull/470 which should not be delayed.  Intent is to clean up the stuff I notice while hunting down the truncated message.
Eliminate copy of malloc `char*` to fixed length `char*`
update `sprintf()` to `snprintf()`
rpt_link.c: Calculate buffer size and malloc buffers. add function __get_buffer_size() to calculate buffer size required. add node count to __mklinklist()
add macro for OBUFSIZE and BUFSIZE calculation
eliminate `finddelim()` call as `__mklinklist()` now counts links.

app_rpt.c: Refactor handle_link_data() and handle_remote_data()

---

apps/app_rpt.c
apps/app_rpt/rpt_cli.c

It appears these calls should be mutex_locked.

app_rpt.c, rpt_cli.c, rpt_manager.c: Add missing mutex_lock()

---

apps/app_rpt.c

No reason to obfuscate the use of the variable here.

app_rpt.c: remove dual purpose of ms variable

---

apps/app_rpt/rpt_config.c

First part of issue #515.
My testing is not confirming the timing behaviors mentioned in the forum -> using debug, the timer runs until `myrpt->linkactivitytimer >= myrpt->p.lnkacttime` at which point it triggers the macro and stops timing.

rpt_config.c: Restore lnkacttimerwarn load logic.

---

apps/app_rpt/rpt_config.c

Found another missing initialization. The clue was that we were initializing votertype 2x.
Also, ASL2 inits these with default 0

rpt_config.c: Add missing votermode load parameter

---

apps/app_rpt.c

Moving the addition of the link to the linked list prevents `ast_waitfor_n` from adding an unfinished link to the list.  If we `return -1` in `rpt_exec()` AFTER adding a link to the `ast_waitfor_n`, the channel pointer is dumped causing a crash.
The main repeater thread is essentially checking every 20ms (max), rebuilding the list of channels and restarting `ast_waitfor_n`.  This can happen much faster if there are messages on the channels.

app_rpt.c: Move link list addition in rpt_exec()

---

apps/app_rpt.c

Shouldn't free the frame before we are done using it.

app_rpt.c: Fix use after free in rxchannel_read()

---

apps/app_rpt.c

At a minimum, we should be locking the write to the buffer just like every other one.
Without it, we may have flaky behavior executing the macro.

app_rpt.c: mutex around link activity macro

---

apps/app_rpt/rpt_link.c

Missing the null terminator in the buffer size calculation.
Elminatates the need for PR #528 and resloves issue #527

rpt_link.c: __get_nodelist_size minimum string size is 1 byte

---

apps/app_rpt.c
apps/app_rpt/app_rpt.h
apps/app_rpt/rpt_channel.c
apps/app_rpt/rpt_channel.h
apps/app_rpt/rpt_link.c

After some struggles understanding newkey logic, I had made these changes for my own sanity.
- add enum for newkey values
- use "good" name for last_keytimer
- Fix comments for 2 to 0 forcing.

Clarify newkey logic with enum

---

apps/app_rpt.c

* Simplify if/else assignments using ternary operator.
* Add macro to simplfy snprintf + pbx_builtin_setvar_helper combo.
* Use pbx_builtin_setvar_helper instead of pbx_builtin_setvar where possible. This is more direct and avoids an unnecessary snprintf with strings where it is immediately split up again.

app_rpt: Simplify variable assignments for Rpt().

---

apps/app_rpt.c

The DTMF timer is using the timer value as a one-shot.  If the timer = 1, we stop counting, then the DTMF logic is supposed to execute 1 time and set the timer value to 0.  
Our timer logic was only checking for a NULL pointer, it should also be checking for a value of 0.
Eliminates the need for https://github.com/AllStarLink/app_rpt/pull/529

app_rpt.c: Fix update_timer logic to stop timing when timer = 0

---

apps/app_rpt.c
apps/app_rpt/mdc_decode.c
apps/app_rpt/mdc_encode.c
apps/app_rpt/pocsag.c
apps/app_rpt/rpt_call.c
apps/app_rpt/rpt_channel.c
apps/app_rpt/rpt_cli.c
apps/app_rpt/rpt_config.c
apps/app_rpt/rpt_daq.c
apps/app_rpt/rpt_functions.c
apps/app_rpt/rpt_link.c
apps/app_rpt/rpt_manager.c
apps/app_rpt/rpt_mdc1200.c
apps/app_rpt/rpt_telemetry.c
apps/app_rpt/rpt_uchameleon.c
channels/chan_echolink.c
channels/chan_simpleusb.c
channels/chan_tlb.c
channels/chan_usbradio.c
channels/chan_usrp.c
channels/chan_voter.c

Many mostly minor stylistic changes to improve compliance with the Asterisk coding guidelines:
* Eliminate return statements at end of void functions.
* Eliminate redundant allocation failure warnings.
* Eliminate superfluous memset calls.
* Eliminate unneeded failure checks.
* Eliminate unnecessary casts from allocations.
* Eliminate some unneeded parentheses.
* Simplify some unnecessarily complicated allocations.

apps, channels: Remove redundant code.

---

apps/app_rpt/rpt_channel.c

tgn was undefined if the TLB branch was not taken.
Resolves: #550

rpt_channel.c: Fix uninitialized memory usage.

---

apps/app_rpt.c

* Abort repeater loop if Asterisk is shutting down.
* Don't try restarting repeaters if Asterisk is shutting down.
This prevents tests from hanging forever and timing out when the test suite attempts to shut Asterisk down.

app_rpt: Shut down repeaters if Asterisk is shutting down.

---

apps/app_rpt.c

Currently, Rpt() rejects all calls received within the first two seconds after the repeater's thread is launched, to give the thread time to start. This is an arbitrary wait time that unnecessarily delays node connects in tests and doesn't guarantee anything is actually started properly. Instead of using an arbitary number for all nodes, look at whether the specific node is actually ready or not yet.

app_rpt: Eliminate START_DELAY and use per-node logic instead.

---

apps/app_rpt.c

Addressing https://github.com/AllStarLink/ASL3/issues/134
When the local repeater times out on TOTIMER, stop transmitting audio and "keyup" to the links from the local inputs.  Link traffic will continue to pass through the node to other connected nodes.

app_rpt.c: Don't keyup link if TOT

---

apps/app_rpt.c
apps/app_rpt/app_rpt.h

Noticed this chunk of code reused a few times.
Add a new `mute_frame_helper()`
Remove unnecessary `memset()` from `mute_frame_helper()`
Rename original `mute_frame_helper()` to `rpt_frame_helper()`
Add macro for muting frames.

app_rpt.c: add rpt_frame_helper and refactor mute_frame_helper

---

apps/app_rpt/app_rpt.h
apps/app_rpt/rpt_cli.c
apps/app_rpt/rpt_functions.c

Parameter size is too small for actual command line parameters.
Index was including a `,` producing a malformed command line.

rpt_cli: Fix rpt cmd <node> cmd. 

---

apps/app_rpt.c

When newkey changes and we were keyedup using the mode RADIO_KEY_NOT_ALLOWED, the IAX channel is stuck keyed up.

app_rpt.c: Address stuck keyup when changing newkey.

---

apps/app_rpt.c
apps/app_rpt/app_rpt.h
apps/app_rpt/rpt_cli.c
apps/app_rpt/rpt_functions.c
apps/app_rpt/rpt_link.c
apps/app_rpt/rpt_link.h
apps/app_rpt/rpt_manager.c
apps/app_rpt/rpt_telemetry.c
apps/app_rpt/rpt_utils.c
apps/app_rpt/rpt_utils.h

Refactor `l->linklist` to use `ast_str`.  This eliminates the limits on connected nodes related to the fixed size of `l->linklist`

app_rpt: Use ast_str for l->linklist

---

.github/workflows/pre-commit.yml

Turns out we need to check ONLY the changed lines.  Diff is causing the entire diff to be checked which causes "growth" in the update.

pre-commit.yml: update lint check

---

apps/app_rpt/rpt_channel.c

ast_stream_and_wait does everything that this function was previously doing manually, except for emitting a warning, which isn't necessary since one will have been logged already in ast_streamfile if needed.

app_rpt: Simplify sayfile logic.

---

apps/app_rpt.c

As suspected, the `send_newkey()` only needs to happen once per connection.
Testing confirmed.

app_rpt.c: Remove unnecessary duplicate send_newkey()

---

apps/app_rpt.c
apps/app_rpt/rpt_cli.c
apps/app_rpt/rpt_functions.c
apps/app_rpt/rpt_link.c
apps/app_rpt/rpt_manager.c
apps/app_rpt/rpt_telemetry.c

Based on PR https://github.com/AllStarLink/app_rpt/pull/545
Use `ast_malloc()` rather than static sizes for `*strs[]`
Eliminate limits imposed by MAXNODES.
Remove MAXNODES define.

Multiple: Eliminate MAXNODES and limits imposed by MAXNODES

---

apps/app_rpt.c

Essentially the "same" math.  No need to roll our own.
Once Asterisk accepts our PR, we will be able to adjust the gains when the specific channel type is created.  This will 100% eliminate the code in calling `ast_frame_adjust_volume_float()`.

app_rpt.c: Use ast_frame_adjust_volume_float()

---

apps/app_rpt.c

indefinite retries for permanent connections
Closing #511

app_rpt.c: Address issue 511 eliminate retry timeout on permanent connections

---

apps/app_rpt.c

Original code was looking for strings in the channel name such that IRLP and Echolink ~~were both in the name~~.  As written, gain applied to `fs` was not making it to the channel because "echolink" != "irlp".  If it's "irlp", no gain is applied, if it's "echolink", gain is applied but not used...
In the end, "irlp" was apparently removed years ago and appears to be a hangover.  All code related to gain and `fs` can simply be removed.

app_rpt.c: fix non channel type "irlp"

---

configs/rpt/echolink.conf
configs/rpt/extensions.conf
configs/rpt/gps.conf
configs/rpt/iax.conf
configs/rpt/rpt.conf
configs/rpt/simpleusb.conf
configs/rpt/usbradio.conf

The configuration files for all ASL nodes require some customization.  Some of the needed changes are for basic settings (e.g. node #, callsign, type of channel driver).  Other changes are to enable various features (e.g. enabling DTMF commands, GPIO usage).  These latter changes tend to require more detailed editing of the configuration files.
This change updates the default configuration files to allow for easier customization.  This is achieved, primarily, by the addition of #tryinclude statements that allow for additional configuration content to be added in separate files.
This change also cleans up some formatting, corrects some spelling errors, updates some abbreviations, etc.

configs: update config files for clarity and improved customization

---

apps/app_rpt/rpt_cli.c
apps/app_rpt/rpt_link.c
apps/app_rpt/rpt_manager.c
apps/app_rpt/rpt_telemetry.c
apps/app_rpt/rpt_utils.c
apps/app_rpt/rpt_utils.h
channels/chan_voter.c

Turns out `explodestring()` and `finddelmin()` need `strs` array to be 1 longer than the count due to a null terminated list requirement.   This is solved by adding 1 to the node count returned by `__mklinklist` and allocating the correct size.

app_rpt: Add 1 to node count for explode string

---

.github/workflows/main.yml
README.md
rpt_install.sh
tests/apps/rpt/fast_connect_disconnect/configs/ast1/extensions.conf
tests/apps/rpt/fast_connect_disconnect/configs/ast1/iax.conf
tests/apps/rpt/fast_connect_disconnect/configs/ast1/logger.general.conf.inc
tests/apps/rpt/fast_connect_disconnect/configs/ast1/modules.conf
tests/apps/rpt/fast_connect_disconnect/configs/ast1/rpt.conf
tests/apps/rpt/fast_connect_disconnect/test-config.yaml
tests/apps/rpt/tests.yaml
tests/apps/tests_apps.diff

As part of work on troubleshooting the issues raised in #459 and #460, add a test to try to capture this condition. The test doesn't reliably capture that issue (it passes most of the time), but it should continue to pass if there is a fix.
Since this is our first test, some changes have been made to rpt_install.sh to allow patching the tests in if the Asterisk test suite is present. The CI also runs the tests now.
Note: This is a test suite (black box) test. Currently, there aren't any unit tests (white box) tests.
Part of #20

tests: Add initial test suite test for fast disconnect.

---

apps/app_rpt.c
apps/app_rpt/rpt_utils.c

Truncating the `macrobuffer` with each shift breaks things.  `ast_str_strlen()` returns the length without NULL, `ast_string_copy()` needs n+1 for null terminator
Fixes #585

app_rpt: fix macrobuffer - ast_copy_string needs +1 for null termination

---

apps/app_rpt.c
apps/app_rpt/app_rpt.h
apps/app_rpt/rpt_link.c

Turns out there is no code to send the message !IAXKEY, so there is no reason to look for said key to arrive.

app_rpt: Remove iaxkey and associated logic

---

apps/app_rpt.c

Updates to snprintf used the sizeof() on a malloc'd string resulting in truncated messages. 
Resolves #589

app_rpt: do_link_post snprintf using wrong size

---

apps/app_rpt.c

Node log should be looking at the value of totx not pointer value.
Resolves #594

app_rpt: incorrect evaluation pointer totx

---

.dev/.clang-format
apps/app_rpt.c
apps/app_rpt/app_rpt.h

AST_FRAME_CNG stops the jitter buffer and codec from interpolating missing frames.
app_rpt intentionally stops sending voice frames to indicate "unkey" to the receiving side.
Specifically when a loud noise (like a squelch burst) occurs in the last frame, the jitter buffer and the codec try to interpolate the missing frames for up to 10 frames.  Sending an AST_FRAME_CNG frame triggers the interpolater not interpolate

app_rpt: If we are unkeyed, send an AST_FRAME_CNG.

---

apps/app_rpt/rpt_link.c
apps/app_rpt/rpt_link.h
apps/app_rpt/rpt_telemetry.c
apps/app_rpt/rpt_telemetry.h

Bit of housekeeping.
static for functions only called in `rpt_telemetry.c`
move `send_tele_link()` to `rpt_telemetry.c` as it's only used in `rpt_telemetry.c`.

app_rpt: static for functions only called in telemetry

---

apps/app_rpt.c
channels/chan_echolink.c

`chan_echolink` was storing a channel pointer which it then attempted to use
after the `ast_channel_yank()`, causing a crash.  This stored pointer was
not necessary and has be refactored to remove it.
Fixes https://github.com/AllStarLink/app_rpt/issues/607

chan_echolink: Echolink channel driver does not handle ast_channel_yank()

---

apps/app_rpt.c

app_rpt: Use previously added macro for sscanf format

app_rpt: Use previously added macro for sscanf format

---

.dev/pre-commit
.devcontainer/devcontainer.json

This commit allows for a codespace to be created with pre-configured commit hooks as well as installing codespell, and clang-format in the container.  
We will need https://github.com/AllStarLink/app_rpt/pull/463 and https://github.com/AllStarLink/app_rpt/pull/466 merged before the pre-commit hook will work properly.

REPO: Add devcontainer configuration

---

apps/app_rpt.c
apps/app_rpt/app_rpt.h
apps/app_rpt/rpt_config.c
configs/rpt/rpt.conf

Setting the `archivedir` variable enables a simple log and audio recording functionality.  Our documentation claimed that the file names would reflect the date and time down to the 1/100 of a second.  In reality, the names were limited to 1 second.
This change adds a new `archivedatefmt` variable allowing one to specify the date/time formatting.  The default format string remains the same but one can now add additional sub-second digits.

app_rpt: add "archivedatefmt" variable for archive date string

---

apps/app_rpt.c
apps/app_rpt/app_rpt.h
apps/app_rpt/rpt_cli.c
apps/app_rpt/rpt_manager.c

The "connection time" available via AMI and displayed by web apps like Allmon3 has not been correct. This was due to accumulating the time using incremental updates. We now report the time since connection was initiated.

app_rpt: report actual "connection time"

---

apps/app_rpt/rpt_manager.c
channels/chan_voter.c

The ordering of the AMI "Response:" and "ActionID:" lines in a reply to an AMI Action is important.  The "Response" needs to be first.

Update/correct AMI "Response:" and "ActionID:" order

---

channels/chan_usbradio.c

By adding 1 null frame (typically at the beginning of a transmission), chan_usbradio can then keep up with the usb device. Generally, the channel update is > 20ms (20.1ms -> 20.5ms) which allowed the usb buffer to empty.  This eliminates the need to set snd_usb_audio lowlatency=0

chan_usbradio: Add 1 null frame when USB buffer is emtpy.

---

apps/app_rpt.c

Just a little "cleanup" on these conference setup calls.  The macros were defined awhile back, looks like these were missed.

app_rpt: Use macros for repeater conference.

---

apps/app_rpt/rpt_utils.c
channels/chan_simpleusb.c
channels/chan_usbradio.c
channels/chan_voter.c

channels: Remove format in text frame and unnecessary initialization.

chan_simpleusb: Remove format text frame and unnecessary init.

---

channels/chan_usbradio.c

Pre PR #244 , this message did not spam the log file, this restores the "one-shot" behavior on keyup

chan_usbradio: Restore previous logging behavior broken in PR #244

---

apps/app_rpt.c

Mode 3 is intended to be a full duplex with local audio muted.  This WAS accomplished via conference settings but that prevented the local audio from reaching the monstream channel. Converting the conference settings to match modes 2 and 4 (full duplex) and simply muting the frames headed to the txchannel allows for monstream to catch the audio and prevent the audio from feeding back on the local speaker. Resolves issue archivedir recording (mostly) silence to WAV file when duplex=3 
Resolves #600

app_rpt: Update duplex mode 3 to pass audio to audioarchive.

---

apps/app_rpt.c
configs/rpt/extensions.conf

First step - allow either "," or "|" but not a mix. Once users have updated we can remove the "|" option
Resolves #133

app_rpt: Use "," in place of "|".

---

apps/app_rpt.c
apps/app_rpt/app_rpt.h
apps/app_rpt/rpt_channel.c
apps/app_rpt/rpt_link.c
apps/app_rpt/rpt_link.h
apps/app_rpt/rpt_mdc1200.c
apps/app_rpt/rpt_telemetry.c

There is no need to queue text message frames on links.  Every "access" to the channel is located in a single thread (`rpt()`) such that simply writing to the channel is all the is needed.

app_rpt: Remove textq

---

apps/app_rpt.c
apps/app_rpt/app_rpt.h
apps/app_rpt/rpt_cli.c
apps/app_rpt/rpt_manager.c

It's possible to have 0 ms values, so we should not update the start time unless we actually have 1ms or more. 
Once we have 1ms, we need to keep the residual usec in the count using `ast_tvsub()` rather than "normal" math.
Use of `ast_tvnow()` can result in negative time measurement with system time changes,  `rpt_tvnow()` uses monotonic time to eliminate negative measurements.

app_rpt: Address negative elap times.

---

apps/app_rpt/rpt_link.c
apps/app_rpt/rpt_telemetry.c

The finddelim() function takes a string and fills a buffer of pointers back to the string.  As such, we should not be referencing those pointers after the passed in string has been free'd.
Note: for consistency, I also re-arranged a few paired calls to ast_free().

Correct a few places where pointers were used after the memory free'd

---

apps/app_rpt/rpt_functions.c
res/res_usbradio.c

Don't crash without access to parallel port.
Allow PP= , pp= , pP=,  or Pp= for parallel port strings.
Allow all cases for GPIO= as well  
Fixes #653
Fixes #654

app_rpt: Don't crash without access to parallel port

---

apps/app_rpt.c
apps/app_rpt/app_rpt.h
apps/app_rpt/rpt_channel.c
apps/app_rpt/rpt_link.c
apps/app_rpt/rpt_link.h
apps/app_rpt/rpt_mdc1200.c
apps/app_rpt/rpt_telemetry.c

This reverts commit 96265a18bdd451b84b9c24bb4f6518f48948ea00. PR #582 
Turns out there are a few async calls to the channel, so we need the queue to only write to the channel while it's not locked.

Revert "app_rpt: Remove rpt_link->textq"

---

apps/app_rpt.c
apps/app_rpt/rpt_bridging.c
apps/app_rpt/rpt_bridging.h

app_rpt: Create `rpt_pbx_run()` to eliminate race conditions between local and remote hangups
where the pbx could/would hangup the channel before `rpt_call()` could finish.
Use `ast_pbx_run_args()` with `no_hangup_chan=1` leaving full control of the channel to `rpt_call()`.
This addresses crashes related to short/invalid dialplans.

app_rpt: Use `rpt_pbx_run` in place of `ast_pbx_start`

---

apps/app_rpt.c

When monitoring multiple nodes our call to ast_frame_adjust_volume_float() was crashing due to a frame with unexpected data.  Specifically:
```
$xx = { frametype = AST_FRAME_VOICE,
subclass = {integer = 0, {format = 0x5556853f28, topology = 0x5556853f28}, frame_ending = 0},
datalen = 0,
samples = 160,
mallocd = 1,
mallocd_hdr_len = 222,
offset = 64,
src = 0x0,
data = {ptr = 0x0, uint32 = 0, pad = "\000\000\000\000\000\000\000"},
delivery = {tv_sec = 1745930822, tv_usec = 19338},
frame_list = {next = 0x0},
flags = 0,
ts = 0,
len = 0,
seqno = 0,
stream_num = 0
}
```
For now, we're going to skip the audio adjustment for these frames.

app_rpt.c: Check frame before adjusting audio

---

.github/workflows/main.yml

Speeds up AI runs to ~2 minutes from original ~10 minutes by only compiling and testing app_rpt and reusing the asterisk build.

Use starter container for ci

---

apps/app_rpt.c
apps/app_rpt/app_rpt.h
apps/app_rpt/rpt_cli.c

The app_rpt CLI parser had expections that all commands would have at least 4 arguments. This limitation prevented using commands like "rpt cmd 2000 status 12" (with only 3 args).  We now check the number of arguments based on the command being used.

app_rpt: allow more "rpt cmd <node> ..." CLI commands

---

apps/app_rpt.c
apps/app_rpt/app_rpt.h
apps/app_rpt/rpt_config.c
configs/rpt/rpt.conf

Adding a new (to ASL3) "archiveaudio" variable that can be used to control whether the both the simple activity log and audio recordings are included in the archive directory.  The variable defaults to "yes" (capture audio) but if set to "no" then only the log will be created (the audio recordings will not be saved).
This added functionality might be used by those who want to keep track of node activity without the added expense (and storage) associated with saving the audio content.

app_rpt: add "archiveaudio" variable to control audio capture

---

tests/apps/rpt/fast_connect_disconnect/configs/ast1/logger.general.conf.inc

A logger.conf was initially included in the test to override the default settings, but these were merged in https://github.com/asterisk/testsuite/commit/7e804d5f7d96dfb78a3195cadec8eae41d020f09 As such, this override file is no longer needed.

tests: Remove no longer needed logger.conf override.

---

README.md
rpt_install.sh

* Use simpler cp commands rather than enumerating all the files we want to copy in the script.
* Remove outdated or old notes in the README that are no longer useful or needed, to make the README more useful to current audiences.

rpt_install.sh: Clean up and simplify script and README.

---

apps/app_rpt.c
apps/app_rpt/rpt_functions.c
apps/app_rpt/rpt_link.c
apps/app_rpt/rpt_manager.c
apps/app_rpt/rpt_telemetry.c
apps/app_rpt/rpt_utils.h
channels/chan_echolink.c
channels/chan_simpleusb.c
channels/chan_tlb.c
channels/chan_usbradio.c
channels/chan_usrp.c
channels/chan_voter.c

- Corrected issue with https://github.com/AllStarLink/app_rpt/pull/602 :
- backed out the switch from ast_queue_frame() to ast_indicate()
- Corrected issue with https://github.com/AllStarLink/app_rpt/pull/658 :
- don't return when holding lock
- Cleanup
- add a "src" to many frames
- when creating frames, use designated initializers
- tweak elapsed time code for readability
- corrected code that wasn't properly handling errors

app_rpt, chan: Fix #602, #658, and some cleanup

---

channels/chan_echolink.c

Address typo in PR #673 - used `AST_CONTROL_RADIO_KEY` where it was `AST_CONTROL_RADIO_UNKEY`

chan_echolink: Not unkeying -> use ast_control_radio_unkey for unkey message

---

apps/app_rpt/rpt_telemetry.c

causes creation of telemetry thread and random keyup.
Related to #648

app_rpt: GPS telemetry incorrect `break;` statement.

---

apps/app_rpt.c
apps/app_rpt/rpt_channel.c
apps/app_rpt/rpt_channel.h
apps/app_rpt/rpt_functions.c
apps/app_rpt/rpt_link.c
apps/app_rpt/rpt_rig.c
apps/app_rpt/rpt_telemetry.c

The "archivedir" variable is used to enable the simple node activity log (key, unkey, link changes) and, optionally, audio recordings.  Here, we are extending the log content to include telemetry information.

app_rpt: add telemetry information to archive logs

---

channels/chan_usbradio.c

With a USBRadio node configuration including `ctcssfrom = no` we are seeing log messages like:
```
[2025-05-21 13:47:52.754] ERROR[115298] ./xpmr/xpmr.c: numrxcodes != numtxcodes
```
This CTCSS RX/TX tone frequencies are not used unless `ctcssfrom = dsp` has been set so this error should never be reported.

chan_usbradio: fix numrxcodes != numtxcodes

---

apps/app_rpt/app_rpt.h
apps/app_rpt/rpt_config.c
apps/app_rpt/rpt_functions.c
configs/rpt/rpt.conf

The "rpt.conf" file had comments about the "parrotmode" variable when, in fact, we were using the "parrot" variable.  This change clears up the comments in the configuration file and its usage in the code.

Resolve parrot mode conflicts between app_rpt, rpt.conf

---

apps/app_rpt.c

This reverts commit 1dadccd83eb6b14b4c7dfa9d5c1cad371068e63b.
While "fixing" audio archive, we "broke" duplex mode 3 original "full duplex" behavior.
First step - back out PR#603, then explore other options to fix audio archive in mode 3.

Revert "app_rpt: Update duplex mode 3 to pass audio to audioarchive."

---

channels/chan_echolink.c

- don't lock/unlock mutex that's already being held

chan_echolink: resolve issues found during code review

---

apps/app_rpt.c

While "fixing" audio archive, we "broke" duplex mode 3 original "full duplex" behavior.  The first step was to back out [PR #603](https://github.com/AllStarLink/app_rpt/pull/603).  That change was made with [PR #707](https://github.com/AllStarLink/app_rpt/pull/707) but the change was incomplete.  This change makes it right.

Revert "app_rpt: Update duplex mode 3 to pass audio to audioarchive (part 2)

---

configs/rpt/rpt.conf

Update Wiki URLs to Github.io ASL3 Manual URLs.
Update references to old sound file locations to be consistent with current ASL3 paths.
Change `lnkacttimerwarn` to a file that actually exists on the ASL3 system.

Update Wiki URLs to ASL3 manual, fix sound file locations for ASL3.

---

channels/chan_voter.c
configs/rpt/voter.conf

Outstanding references in voter.conf and chan_voter.c to the old port 667/UDP, which has now been changed to 1667/UDP by default.
Some are documentation changes, except for listen_port, which defines the default port if the port option isn't set in voter.conf.
UpgradeNote: ASL3 documentation specifies the change to port 1667/UDP, however, if users omitted the port=1667 option in voter.conf, chan_voter would have defaulted to the "old" port 667/UDP. This change will cause the default port to be the expected "new" port 1667/UDP.

app_rpt: Update missed/default UDP port references 667 --> 1667

---

channels/chan_echolink.c

Move comment on incorrect line.

chan_echolink: Correct comments on KEEPALIVE_TIME

---

apps/app_rpt/rpt_bridging.c

`rpt_stop_tone` calls `rpt_play_tone` with `-1`.  Reviewing the original code, this should send a `-1` to `tone_zone_play_tone()`. 
-1 was not possible.

app_rpt: rpt_play_tone incorrectly handling rpt_stop_tone.

---

apps/app_rpt/rpt_call.c

Potential memory leak by not freeing `cap` when failures occur.

app_rpt: rpt_call.c address `cap` memory leak

---

channels/chan_usbradio.c
channels/xpmr/xpmr.c
channels/xpmr/xpmr.h

With some users not dialing in their RX audio levels and/or not tapping off audio before de-emphasis, you get wildly varying audio levels depending upon what you're listening to. If your node is using the txprelim setting, I've noticed that some users are so loud that they cause the deviation to exceed 5 kHz and therefore the users of the adjacent channel could experience interference.
Some background: The txprelim setting is used when you want to use pre-emphasized and limited  "flat audio". In my case, I used Motorola CDM 1250's with the audio input on the rear connector set to flat audio with no limiting. In versions of the chan_usbradio.c and xpmr.c  source code prior to this pull request the tx soft limiter was hardcoded to a value of 12000. What I noticed with this hard coded value …

Add TX soft limiter adjustment to chan_usbradio.c, xpmr.c, and xpmr.h.

---

apps/app_rpt.c
apps/app_rpt/app_rpt.h
apps/app_rpt/rpt_config.c
configs/rpt/rpt.conf

Picket fencing on a stuck key causes timeout to reset too quickly.  Need a bit of delay on unkey before resetting the Timeout Timer and rekeying the machine.
This can be disabled to match previous behavior.

app_rpt: Add timeout reset delay via `toresettime` parameter.

---

README.md

I thought it might be good to update README.md file on code prettifying, as running the indent command was not the correct thing to do.
I updated this section of the README.md to use clang-format instead. I also added a note not to do prettification if there are only a few lines of code being touched.

Update README to use clang-format for code prettification

---

channels/chan_simpleusb.c
channels/chan_usbradio.c

chan_simpleusb:
address incorrect limit on o->txoffcnt.
Add limits to txoffdelay and rxondelay.
Fixes #745 
Seems like 1 minute on/off delay is plenty of time for this configuration.

chan_usbradio & chan_simpleusb: add limits.

---

configs/rpt/simpleusb.conf

Remove invalid options `txmixa` and `txmixb`. Update definitions.
`txmixa` and `txmixb` are not valid options for `chan_simpleusb`. Remove them from the default .conf file. Update descriptions of `rxondelay` and `txoffdelay` for better clarity of what they do, and how they interact with each other. Correct description that default option for `eeprom` is `1` (not `0`). Add link to ASL3 Manual page for `simpleusb.conf`. 
Closes #746

simpleusb.conf: Remove invalid options txmixa and txmixb. Update definitions.

---

channels/chan_voter.c

Current debug message levels have repeating/streaming messages in low debug levels, preventing effective troubleshooting. This change moves those repeating/streaming messages to higher levels, as they typically are not required for normal debugging.

voter.c: Revise debug message levels for easier troubleshooting.

---

apps/app_rpt/rpt_link.c

Allowing cli rpt playback to send audio out the links as expected.
Fixes #773 
This one appears to have been around since ASL2.  Further testing to confirm it doesn't break anything else would be appreciated as I'm not sure I completely understand what this configuration is doing.

app_rpt.c: Handle `duplex=0` with `linktolink=yes`

---

channels/chan_simpleusb.c
channels/chan_usbradio.c
channels/xpmr/xpmr.c
include/asterisk/res_usbradio.h
res/res_usbradio.c
utils/radio-tune-menu.c
utils/simpleusb-tune-menu.c

Fix issue 791 in xpmr.c. Add Tx Audio Stats utility. See https://github.com/AllStarLink/app_rpt/issues/791 for details. As noted in one of my comments there this is a somewhat major issue that will affect all nodes using USBRadio channel driver, regardless of if txboost is on or off or other usbradio.conf settings.
I have included the Tx Audio Stats utility with this as it was very helpful in testing an is a very simple change extending the already existing Rx Audio Stats utility to now also be able to look at Tx audio.

Channel drivers, tune utilities: add Tx Audio Stats, fix issue 791
